#!/usr/bin/env python3
"""
Assembles LGAM subpages from shared partials + per-page content.
Run from anywhere: python gds-local/_build/build.py

Zero external dependencies — uses only Python stdlib.
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GDS_LOCAL_DIR = os.path.dirname(SCRIPT_DIR)
PARTIALS_DIR = os.path.join(SCRIPT_DIR, "_partials")
PAGES_DIR = os.path.join(SCRIPT_DIR, "_pages")

GENERATED_COMMENT = "<!-- Generated by build.py — do not edit directly -->\n"


def read_partial(name):
    with open(os.path.join(PARTIALS_DIR, name), "r", encoding="utf-8") as f:
        return f.read()


def parse_page(filepath):
    """Parse a page source file into front matter dict and content blocks."""
    with open(filepath, "r", encoding="utf-8") as f:
        raw = f.read()

    # Parse front matter
    if not raw.startswith("---"):
        raise ValueError(f"{filepath}: missing front matter (must start with ---)")

    end = raw.index("---", 3)
    fm_block = raw[3:end].strip()
    body = raw[end + 3:].strip()

    front_matter = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, val = line.split(":", 1)
            front_matter[key.strip()] = val.strip()

    # Extract tagged blocks
    def extract_block(tag):
        pattern = f"<{tag}>(.*?)</{tag}>"
        m = re.search(pattern, body, re.DOTALL)
        return m.group(1) if m else ""

    blocks = {
        "style": extract_block("style"),
        "nav_contents": extract_block("nav-contents"),
        "main_content": extract_block("main-content"),
        "page_script": extract_block("page-script"),
    }

    return front_matter, blocks


def build_page(filename, front_matter, blocks):
    """Assemble a full HTML page from partials and page-specific blocks."""
    head_open = read_partial("head-open.html")
    layout_css = read_partial("layout-css.html")
    header = read_partial("header.html")
    sidebar_lgam = read_partial("sidebar-lgam.html")
    footer = read_partial("footer.html")

    # Replace template variables in head
    title = front_matter.get("title", "Page")
    head_open = head_open.replace("{{ title }}", title)

    # Assemble
    parts = []
    parts.append(GENERATED_COMMENT)
    parts.append(head_open)

    # Page-specific CSS
    if blocks["style"].strip():
        parts.append(blocks["style"])
        parts.append("\n")

    # Layout CSS
    parts.append(layout_css)
    parts.append("  </style>\n</head>\n\n")

    # Body: header + phase banner
    parts.append(header)
    parts.append("\n")

    # Content wrapper with sidebar + main
    parts.append("  <div class=\"app-content-wrapper\">\n")
    parts.append("    <nav class=\"app-sidebar\" aria-label=\"Page navigation\">\n")
    parts.append("      <h2 class=\"app-navigation__heading\">Contents</h2>\n")
    parts.append("      <ul class=\"app-navigation\">\n")
    parts.append(blocks["nav_contents"])
    parts.append("\n      </ul>\n")
    parts.append(sidebar_lgam)
    parts.append("    </nav>\n\n")
    parts.append("      <main class=\"app-main-content\" id=\"main-content\" role=\"main\">\n")
    parts.append(blocks["main_content"])
    parts.append("\n      </main>\n")
    parts.append("  </div>\n\n")

    # Footer
    parts.append(footer)

    # Page-specific script
    if blocks["page_script"].strip():
        parts.append("\n  <script>\n")
        parts.append(blocks["page_script"])
        parts.append("\n  </script>\n")

    parts.append("</body>\n</html>\n")

    return "".join(parts)


def update_index_links(pages):
    """Insert/remove 'View X detail' links in index.html based on page status."""
    index_path = os.path.join(GDS_LOCAL_DIR, "index.html")
    if not os.path.exists(index_path):
        print("  [skip] index.html not found")
        return

    with open(index_path, "r", encoding="utf-8") as f:
        html = f.read()

    original = html

    for filename, fm in pages:
        title = fm.get("title", "")
        status = fm.get("status", "draft")
        if not title:
            continue

        # Build the link paragraph we want to insert/find
        link_para = (
            f'<p class="govuk-body govuk-!-margin-top-3 govuk-!-margin-bottom-0">'
            f'<a href="{filename}" class="govuk-link">View {title} detail &rarr;</a></p>'
        )

        # Pattern to find existing auto-generated link for this file
        link_pattern = re.compile(
            r'<p class="govuk-body govuk-!-margin-top-3 govuk-!-margin-bottom-0">'
            r'<a href="' + re.escape(filename) + r'"[^>]*>View [^<]+ detail[^<]*</a></p>\n?'
        )

        # Find the item whose summary text matches the page title (case-insensitive)
        # Pattern: <summary...><span...>Title text</span></summary>
        summary_pattern = re.compile(
            r'(<details[^>]*>.*?<summary[^>]*>\s*<span[^>]*>)\s*'
            + re.escape(title)
            + r'\s*(</span>\s*</summary>.*?<div class="govuk-details__text">)(.*?)(</div>\s*</details>)',
            re.DOTALL | re.IGNORECASE,
        )

        match = summary_pattern.search(html)
        if not match:
            continue

        details_text = match.group(3)

        if status == "published":
            # If link already present, leave it
            if link_pattern.search(details_text):
                continue
            # Insert link after the first <p> in the details text
            # Find end of first paragraph
            first_p_end = re.search(r'</p>', details_text)
            if first_p_end:
                insert_pos = match.start(3) + first_p_end.end()
                html = html[:insert_pos] + "\n                    " + link_para + html[insert_pos:]
        else:
            # Draft: remove link if present
            html = link_pattern.sub("", html)

    if html != original:
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(html)
        print("  [updated] index.html")
    else:
        print("  [unchanged] index.html")


def main():
    if not os.path.isdir(PAGES_DIR):
        print(f"Error: pages directory not found: {PAGES_DIR}", file=sys.stderr)
        sys.exit(1)

    page_files = sorted(
        f for f in os.listdir(PAGES_DIR) if f.endswith(".html")
    )

    if not page_files:
        print("No page sources found in _pages/")
        return

    print(f"Building {len(page_files)} page(s)...")

    pages_meta = []

    for filename in page_files:
        filepath = os.path.join(PAGES_DIR, filename)
        fm, blocks = parse_page(filepath)
        output = build_page(filename, fm, blocks)

        out_path = os.path.join(GDS_LOCAL_DIR, filename)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(output)

        status = fm.get("status", "draft")
        print(f"  [built] {filename} (status: {status})")
        pages_meta.append((filename, fm))

    # Update index.html links
    print("\nUpdating index.html links...")
    update_index_links(pages_meta)

    print("\nDone.")


if __name__ == "__main__":
    main()
